### ISSUE TITLE
Bugs/suggestions on alpha version

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openpath-dash#1]
## Dropdowns / making selections
- [ ] Meaning of `Show raw practice-level data` wasn't immediately clear - could rephrase as `Include a data table` or similar
- [ ] Selecting chart type could be separated from the other dropdowns, perhaps as tabs (as in OP Analyse page) or buttons. Tabular data could be one of the tabs/buttons rather than displayed under a chart. 
- [ ] Would it be better to have a button to generate chart rather than doing it automatically? If you're changing a few things it can be a bit slow while it generates each one - particularly if you have a slow NHS computer/connection!
- [ ] Ideally we'd make a component that removes "All tests" when you add a specific test. Unfortunately this involves writing quite a lot of boilerplate code and might take too long for the time being.  Seb has added comments in the code somewhere about how this would be done 

## Noise
- [ ] Could we have an option (perhaps selected by default) to exclude practices with less than say 12 months of data - or a sliding scale?
- [ ] And/or practices with data in the last month (maybe tricky when end dates are different for each trust)
- [ ] And/or a filter for denominator e.g. 50 tests total/last month (sliding scale probably necessary) or 500 patients

## Charts
- [x] **The errors from low number suppression are way too high** across the board for proportions - looks like the values are not being divided by the denominator ![image](https://user-images.githubusercontent.com/24392156/67563625-f993ce80-f718-11e9-9413-cf1c66153609.png)
![image](https://user-images.githubusercontent.com/24392156/67563711-27791300-f719-11e9-8a71-edf1f49e3283.png)
([raw](http://dash.openpathology.net/apps/deciles/by/practice/showing/ccg_id/11N+15N/numerators/TSH/denominators/TSH/filter/under_range)) 
([proportion](http://dash.openpathology.net/apps/deciles/by/practice/showing/ccg_id/11N+15N/numerators/TSH/denominators/TSH/filter/under_range))
- [ ] As well as "download" is is possible to add "copy to clipboard"?
- [ ] When grouping by result the heatmaps don't display the meaning of the numeric codes (-1, 0, 3, 6 etc) ([link](http://dash.openpathology.net/apps/heatmap/by/result_category/showing/ccg_id/11N+15N/numerators/TSH/denominators/per1000/filter/all))
- [ ] When grouping by result it's not possible to see these as a proportion (i.e. proportion of TSH tests which are above, below, etc) ([link](http://dash.openpathology.net/apps/heatmap/by/result_category/showing/ccg_id/11N+15N/numerators/TSH/denominators/TSH/filter/all))
- [ ] The text indicating the groupby selection is not human-friendly (e.g. `test_codes` [here](http://dash.openpathology.net/apps/heatmap/by/test_code/showing/ccg_id/all/numerators/GENT/denominators/per1000/filter/all))
## Chart titles
- [ ] It would be handy to be able to copy chart titles as text rather than images!
- [ ] Practice decile chart titles needs addition of "entity" in front of practice ref no. ([link](http://dash.openpathology.net/apps/deciles/by/practice/showing/ccg_id/11N+15N/numerators/TSH/denominators/per1000/filter/within_range))
![image](https://user-images.githubusercontent.com/24392156/67559875-b1bd7900-f711-11e9-84e0-10d5a0808343.png) 
- [ ] When showing raw numbers the chart titles say "as a proportion of raw" ([link](http://dash.openpathology.net/apps/deciles/by/practice/showing/ccg_id/11N+15N/numerators/TSH/denominators/raw/filter/under_range)).

**Comment by sebbacon** [comment]
Example of outliers throwing viz: 
![image](https://user-images.githubusercontent.com/211271/68109662-05368080-fee3-11e9-9e2b-e91843324594.png)

**Comment by sebbacon** [comment]
# Dealing with larger amounts of data

* [ ] How important/useful is the data table? As the dataset size grows we will need to make this scaleable (currently it's all the data in memory, can make it pageable etc)
  - HC: not very useful I think but local clinicians etc might like to have it
* [ ] How should we deal with larger numbers of practice-level decile charts? It will become too slow very quickly. We could remove interaction, or build a load-on-scroll widget (I think this will take too long), or add paging, or...?
  - HC: Allow only one CCG (or one trust) to be selected at once if looking at this type of chart?

# Reducing the number of dead ends

I don't like that it's so easy to select meaningless charts. Examples:

* [ ] Some of the error filters result in empty charts ([e.g.](http://dash.openpathology.net/apps/heatmap/by/practice/showing/ccg_id/all/numerators/UREA/denominators/per1000/filter/5))
  - HC: I wouldn't bother with the error filters yet except maybe the most common one or two, but easier to just skip them entirely. 
* [ ] Something as a proportion of anything other than itself is usually pointless? (Check with Tom/Rich though) ([e.g.](http://dash.openpathology.net/apps/heatmap/by/practice/showing/ccg_id/all/numerators/UREA/denominators/CREA/filter/all))
  - HC: well that would be a ratio rather than a proportion, which can be useful... However, probably only if you're looking at "all tests" rather than filtering (the numerator) to positive/negative results. 
* [ ] It shouldn't be possible to filter by reference range for tests without reference ranges ([e.g.](http://dash.openpathology.net/apps/heatmap/by/ccg_id/showing/ccg_id/all/numerators/HDLR/denominators/per1000/filter/within_range))
  - Agree
* [ ] Does it make sense to allow grouping by something when there is only one of it? [e.g. grouping by test code for one test](http://dash.openpathology.net/apps/heatmap/by/test_code/showing/ccg_id/all/numerators/GENT/denominators/per1000/filter/all)
  - HC: yes, because this allows you to see the aggregated data across all practices/CCGs which can be useful. However this isn't an essential feature necessarily and we could add this to other views if possible.
This is tangentially related to some of @HelenCEBM's suggestions about suppressing noise

**Comment by HelenCEBM** [comment]
- @sebbacon I've added my thoughts to your comment above.
- it seems we might have to define which order you have to select each filter?
- also a trust filter might be useful rather than just CCG as some trusts serve only part of a ccg, or several, and as we know the test-ordering options you get might be determined by your trust not your ccg.

**Comment by HelenCEBM** [comment]
- [ ] we should make it obvious that the results-above/below filter applies to the numerator only

**Comment by HelenCEBM** [comment]
When you click on a heatmap it opens decile charts but it's not obvious that is what will happen and it doesn't highlight the practice you clicked on so it's not really a helpful feature - could it be either disabled, or an option when you click on the heatmap, rather than loading automatically?

Another issue with this is that it still has the "Heatmap" tab selected when it's loaded the deciles, and so you can't switch back to heatmap view easily.
