### ISSUE TITLE
Practice-level data table broken for various queries

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openpath-dash#119]
The data table view loads OK for "per1000" and "absolute number" queries, but it throws an error for everything else e.g. proportion within ref range.

In trying to fix this I've realised I am confused about what this view is actually supposed to be doing. There are two sorts of data table view that _do_ make sense to me:

 1. A view which is simply the same data displayed in the heatmap but in tabular, downloadable form.

 2. A view which contains the most granular data we have (i.e. at month-practice-test-result_category level) filtered by the current selected tests (and optionally lab or CCG if they are selected).
 
In case 2, the "Showing" and "Group by" dropdowns are irrelevant to the contents of the table. And there can be no numerator, denominator or calc value columns as those aren't defined at this level.

What's confusing me is that current data table view seems to be neither of these things, or a weird mixture of the two.

Am I missing something?

Fixing this is also a pre-requisite of fixing #89

**Comment by sebbacon** [comment]
I believe it began as (1) but (2) became useful for the immediate use-case facing me, which was debugging some kind of issue in the data. You're now victim to me not having thought about it since then, I'm afraid. Apologies!

I think (1) is what most people would expect - but I don't have strong feelings about this as we don't really have a real end-user use case. The only hard requirement is some way of offering data downloads in the broadest sense - we could potentially just offer the full source file, for example.  Please feel free to pick a solution that feels sensible and clean!

**Comment by evansd** [comment]
Great, thanks! I think 1 will actually be the easiest to implement and, if we just rename the tab to "Data table" or something like that then I think it should be fairly obvious to the user.
