### ISSUE TITLE
Heatmap colours not making sense

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#129]
This is for "[proportion non-numeric](http://dash.openpathology.net/data/chart/by/test_code/showing/ccg_id/all/lab_id/all/numerators/all/denominators/all/filter/3)":

![image](https://user-images.githubusercontent.com/211271/70921336-01d30080-201c-11ea-8865-613085d2dba9.png)

For example, `VALP` in Sept 2014 is yellow, indicating a high value, yet it's 0/6 according to the mouseover.  I also noticed some of the cells have no mouseover behaviour; perhaps it's the labelling that's wrong, rather than the colours?

**Comment by evansd** [comment]
This is actually another manifestation of the same underlying weirdness that led to this:
https://github.com/ebmdatalab/openpath-dash/blob/8645db845565c31e1ac0af105a76a54799c8e782/apps/heatmap.py#L145-L158

i.e. it's an off-by-one error where Dash is showing hover info for the row _below_ the one you're hovering over.

It's going to take me a while longer to work out what the underlying issue is.

**Comment by evansd** [comment]
RIGHT. I'VE GOT IT.

By doing a binary search by hand on lists of things which worked and things which didn't, I have determined that the problem is ... our human readable test names aren't unique. `GLU` and `GLUX` both map to "Glucose". And using duplicated y-axis labels confuses the heatmap and leads to the off-by-one error.

**Comment by sebbacon** [comment]
Ah the old binary search on random guesses, ultimately very satisfying! HIGH FIVE EVANSD!

As you mention in the PR, in fact this should never happen - we have a prototype, mainly-manual system managed by @HelenCEBM for normalising test codes - but it's pretty hard to get all the edges right.
