### ISSUE TITLE
Resolve list size oddities

### ISSUE THREAD

**Issue by richiecroker** [ebmdatalab/openpath-dash#140]
List sizes seem variable at both CCG and lab level - more that we'd expect from openprescribing data.
![image](https://user-images.githubusercontent.com/18683239/71207569-13780a80-229f-11ea-94ba-e88a44118c21.png)

![image](https://user-images.githubusercontent.com/18683239/71207576-196deb80-229f-11ea-8a46-dd260ea6d6b7.png)

**Comment by richiecroker** [comment]
for example list size changes by considerable amount in Dec 18 cf Nov 18:

Labs: 
- ND 204,003 vs 188,673 (15,330)
- Plymouth 414,787 vs 364,278 (50,509)
- Truro 503,929 vs 542,064 (-38,135)

Net change for Dec 18 vs Nov 18: 27,704

CCGs;
- Devon 527,766 vs 516,662 (11,104)
- Kernow: 578,815 vs 578,353 (462)

The sums of these also do not always match each other:

November 2018:
- Labs: 1,095,015
- CCGs:  1,095,015 (match)

December 2018:
- Labs: 1,122,719
- CCGs: 1,106,581 (difference: 16,138)

**Comment by sebbacon** [comment]
Having looked into this, the reason is that we are taking "ccg list size" as being "sum of all the practices that did any tests in that month" rather than "sum of all the practices in that month".  For example, `L85012` is about 15,000 people and made test requests to North Devon in December 2018 but not November.

The correct definition of a CCG list size is the one we use on OpenPrescribing, and should be calculated separately - this is a bug.

However, the correct definition of a Lab list size is slippery.  All we can do is take "practices that made any test requests in a month" and use this as a virtual list size. However, this definition makes "list sizes" quite inconsistent month-to-month and therefore potentially less useful as a denominator.

There are three options I can think of:

1. Do nothing - but document this as an oddity
2. Use a heuristic to remove odd outlier practices (based on the hypothesis that these are weirdies that we shouldn't really care about) -- either something like "all practices that make fewer than 50 potassium requests per quarter" or, perhaps, just applying the existing low-number-filtering to denominators?
3. Use some kind of smoothing like 3 month moving averages, medians, etc

**Comment by sebbacon** [comment]
Of course, this presents a challenge, as there is no definition for lab size other than "practices who did tests in that month"...

**Comment by HelenCEBM** [comment]
Here's an example of why 50 Ks is a good limit: 
The highlighted point is for 37 potassiums in one month at ND in a practice which usually does none - the other odd dots and darkest shades are pretty much all "3" (i.e. suppressed low number)
![image](https://user-images.githubusercontent.com/24392156/71264919-09a4e480-233d-11ea-8658-37e8ce9fe576.png)

**Comment by HelenCEBM** [comment]
Before applying the low number filter only to the per-1000 measures (which seems sensible) we should consider whether it's likely to cause confusion (e.g. "why isn't this practice shown when I look at tests per 1000 but it is when I look at ratios?")

**Comment by richiecroker** [comment]
Reopened, as there is still an issue.

There was still variation of approx 15k between list sizes of two months of data for potasssium requests for Plymouth.  Having looked at the data, it appears to relate to Beaumont Villa practice (L83018) causing the issues in this case.  Until April 2018 it's reported as doing several hundred `K` per month, since then it has reduced significantly, but crucially, wavering between <50 and >50. 
![image](https://user-images.githubusercontent.com/18683239/72338427-5f5e7980-36bc-11ea-9707-8cfef167cd3d.png)

Beaumont Villa practice is a practice which has become part of a larger medical group (Pathfields) in Plymouth.  About 6 surgeries have merged.  Unlike the rest of the group that are all listed now under Pathfields ODS code (L83008), it seems Beaumont Villa has not changed its code.  Therefore we're still seeing list sizes as around 14-15k

But we are seeing their data disappearing from Beaumont Villa and into the Pathfields code:
![image](https://user-images.githubusercontent.com/18683239/72338483-74d3a380-36bc-11ea-8f4e-3d894561eaac.png)

The issue appears to be (although we need to ask) that this must be wrapped up in the way that ICE works, or interacts with their LIMS - i.e. is it transmitting _requester_ ODS code or _patient_ ODS code.
We don't see this replicated in the prescribing data, as the prescribing system sends the ODS code for the registered patient's GP, which in this case is still Beaumont Villa

This is a wider issue in Plymouth, which has seen many mergers recently.  E.g. L83006 which has since a massive list size increase due to merger, but probably not allocation of pathology data.
![image](https://user-images.githubusercontent.com/18683239/72338617-c8de8800-36bc-11ea-8706-e36f82977b97.png)

Question is, how do we fix?  I'm not sure <50 `K` threshold works for this.

**Comment by evansd** [comment]
Thanks @richiecroker. Can you create a new issue for this though? The old one turned out to be a mixture of different problems and the more focused we can keep the issues the easier it is to keep track of things.

**Comment by richiecroker** [comment]
will do @evansd
