### ISSUE TITLE
per1000 denominator appears to be wrong

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#94]
Population sizes at L83008 ([link](http://dash.openpathology.net/data/chart/by/practice_id/showing/ccg_id/all/lab_id/plymouth/numerators/K/denominators/per1000/filter/all?highlight_entities=L83008))

```
15N,L83008,PATHFIELDS MEDICAL GROUP,2019-03-01,11211.0
15N,L83008,PATHFIELDS MEDICAL GROUP,2019-04-01,11215.0
15N,L83008,PATHFIELDS MEDICAL GROUP,2019-05-01,17962.0
```

But heatmap for per1000 shows something very different for the denominators:

![image](https://user-images.githubusercontent.com/211271/70051420-e6520980-15c8-11ea-8526-fd79f6078820.png)

**Comment by sebbacon** [comment]
Perhaps tangentially related to #89?

**Comment by evansd** [comment]
Right, I know what the issue is here but it might take me a while to figure out the correct Pandas incantation to fix it.

The problem is in these lines here:
https://github.com/ebmdatalab/openpath-dash/blob/bd30b085d41fceb4e824b36f0b269195416e3d28/data.py#L150-L155

The `.sum()` call sums all columns, which includes `total_list_size`. So each practice's list size ends up being multiplied by a factor of however many (test code, result category) pairs there are in the data for that practice. Observe that if you look at per1000 for all tests then the list size numbers get much larger than they are for a single test.

What we want is for counts to get summed, but nothing else. But I don't know the easiest way of achieving that.

**Comment by sebbacon** [comment]
Ah OK so I think you want to do something like 

```python
num_df_agg = filtered_df
num_df_agg['numerator'] = num_df_agg[cols].groupby(groupby).sum()['numerator']
```

**Comment by evansd** [comment]
I've tried that (using `"count"` instead of `"numerator"`) but it raises
```
TypeError: incompatible index of inserted column with frame index
```
And I don't have enough of a mental model of what Pandas is doing to understand how to fix that.

**Comment by inglesp** [comment]
Let me know if I can help.

**Comment by evansd** [comment]
Peter and I looked at this for a bit. One suggestion Peter had was to add `total_list_size` to the `groupby`. This does the right thing when grouping by practice_id, but not when grouping by ccg_id or lab_id where we do want to sum `total_list_size` but only once per practice, rather than once per row of data.

I think we need to pull all the list sizes into a separate dataframe and do the aggregation there before writing back to the main dataframe. I'll look into trying to do this.

**Comment by sebbacon** [comment]
Yes, this sounds right to me.  Join the denominators dataframe (or just the per1000 one?) at the point we need it.
